import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Container from "@/components/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="flex flex-col h-screen justify-between">
            <body className={inter.className}>
                <Container>
                    <Navbar />
                    {children}
                </Container>
            </body>
            <footer>
                <p className="text-center p-4">Copyright Art Vault 2024 ©</p>
            </footer>
        </html>
    );
}
